### ISSUE TITLE
Creating a pull request

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#49]
[Create a feature branch and a pull request for your work](https://github.com/StoneyJackson/github-workflow-activity/blob/doc-per-task/activity/contribution-workflow.md#create-a-feature-branch-and-a-pull-request-pr-for-your-work)

Regarding step 8 -- I don't see "New pull request" -- Here's what I see instead
![image](https://user-images.githubusercontent.com/2592132/41314319-776337a4-6e5a-11e8-982f-f70c316cca46.png)

When I click "Compare and pull request", then I get the following:
![image](https://user-images.githubusercontent.com/2592132/41314504-efe09a8c-6e5a-11e8-834e-ffba4c2544fd.png)

This is what you were expecting!

I clicked "Create pull request" and then got the following:
![image](https://user-images.githubusercontent.com/2592132/41314817-cb1926d2-6e5b-11e8-894c-35a62479a3a1.png)

I added a comment about what I was doing and then step 12 says to "Create pull request", but this is not an option for me. Not sure what to do at this point...

**Comment by StoneyJackson** [comment]
There is a "New pull request" but it is a subtle grey button. The big green button on the right is more obvious. The problem is, that big green button is not always there. I'll change this step to "7. Open a PR by clicking __New pull request__ (subtle grey button in the middle) or __Compare & pull request__ (big green button on the right)."

You see why I prefer command-line over GUIs :)

I've also reordered the steps to fix the dead end that you reached.
