### ISSUE TITLE
Ordering of steps 

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#53]
This is likely because I have the old workflow more ingrained in my mind, but it seems counter intuitive to create a PR before doing the work. I haven't looked, but does the updated .pptx file illustrate this process?

**Comment by StoneyJackson** [comment]
Right. I've heard folks from GitHub talking about open a PR early for the sake of discussion. I also like it because it allows other developers to track your progress and see that you are actually working on it (and not left wondering if you abandoned the effort or gave up without telling anyone).

Normally the suggestion is to open a PR just after you have a little something to show folks (a mockup, a unit test, etc.). This workflow goes to the extreme and aks you to open a PR immediately. The reason for this is compartmentalization. By opening a PR immediately it allows us to move it and all the work to create a feature branch into a setup phase. So all the special, one-time operations like `git push -u origin FEATURE` (note the `-u` is only used the first time the branch is pushed) and opening a PR is moved into the setup phase. Thereafter, the rest of the workflow becomes uniform: make, stage, commit, push, repeat. No more writing things like, "if you haven't created a PR yet, do so now" or "if this is the first time you are pushing to your fork use `-u`", etc. It just makes this stuff cleaner (IMHO).

No, the presentation does not demonstrate this. Let me think about adding this.

**Comment by StoneyJackson** [comment]
Added explanation in contribution-workflow.md
