### ISSUE TITLE
Close the issue

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#56]
Step 6 in the Readme should include instructions to close the issue.

**Comment by StoneyJackson** [comment]
Folks now add the issue number to a PR preceding it with "Closes"... so "Closes #i". I also added a note that tells participants that when the PR is merged, issues mentioned this way will automatically be closed.

Could do more here. But it would probably be on the maintainer side of things. For example, maintainers should probably look through existing issues and see which if any they address. The maintainer could add a comment about the issues this PR would close, and then close the PR. Or the maintainer could tidy up issues after the merge. More likely, during development, both the maintainer and the contributor, and possibly other developers, would add such comments in the PR so that when the PR is merged everything is automatically tidied up.

Sorry for the long message. Just brain dumping.
